CREATE DATABASE cdr;
\c cdr;

CREATE TABLE transaction (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             call_type CHAR(2) NOT NULL,
                             first_number CHAR(11) NOT NULL,
                             second_number CHAR(11) NOT NULL,
                             start_time BIGINT NOT NULL,
                             end_time BIGINT NOT NULL
);

CREATE TABLE external_client (
                                 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 number CHAR(11) NOT NULL UNIQUE
);

CREATE TABLE internal_client (
                                 id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 number CHAR(11) NOT NULL UNIQUE
);

CREATE DATABASE brt;
\c brt;

CREATE TABLE client (
                        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        phone_number CHAR(11) NOT NULL UNIQUE,
                        name VARCHAR NOT NULL,
                        balance MONEY,
                        tariff_id INTEGER
);


